### ISSUE TITLE
feedback on processPeerShare function

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#16]
Comments on https://github.com/WhoSoup/factom-p2p/blob/master/controller_cat.go#L42

1. Shouldn't you return early line 46 after the error?
2. I'd say a peer sending bad data warrant a warning for logging, as it seems the only reason for that would be a rogue node, so I think it should stand out
3. It discrepency of validation between  Endpoint#Valid and NewEndpoint() is a bit odd... NewEndpoint allows the creation of an Endpoint with invalid port, and Valid() allows an endpoints with an invalid IP format. It's a bit odd and deceptive, what I'd do is have Valid do a full validation (aka add parsing of the IP address) and then have NewEndpoint rely on this solid Valid to be sure to instanciate a valid endpoint.
4. Why is the Prometheus gauge KnownPeers refreshed at the end? Maybe I am overlooking a side effect, but it doesn't seem that `c.peers.Total()` would have been modified during the execution of this function?

**Comment by WhoSoup** [comment]
1. Yes, good catch
2. Yes and no. A rogue node would probably send a json message containing bad data, rather than a malformed json message that can't be unmarshaled. The likeliest reason someone would send broken json is a third party developer with a buggy implementation, which I would count as non-malicious
3. Yeah, P2P1 sort-of supported hostnames to be used, but the cost of verifying a hostname is accurate (ie it can be resolved) is too costly to perform in most contexts and is automatically handled by the dialing process. The suggestion is good but I'm considering just dropping the validation of the ip entirely (except for an empty check). I'll investigate it further to see how it interacts with hostnames and docker containers first.
4. Leftover from P2P1 functionality, will remove it

**Comment by PaulBernier** [comment]
On the Endpoint validation:
I see that you have places where an Endpoint with no port seems to be acceptable: https://github.com/WhoSoup/factom-p2p/blob/master/controller_connections.go#L142 but now that doesn't go well with you Endpoint#Valid function that would reject such an Endpoint. If you want to use that fallback value mechanism, maybe put it in NewEndpoint directly? (i.e NewEndpoint can be called without a port and in this case it will be automatically filled with the listen port)

**Comment by WhoSoup** [comment]
> On the Endpoint validation:
> I see that you have places where an Endpoint with no port seems to be acceptable: https://github.com/WhoSoup/factom-p2p/blob/master/controller_connections.go#L142 but now that doesn't go well with you Endpoint#Valid function that would reject such an Endpoint. If you want to use that fallback value mechanism, maybe put it in NewEndpoint directly? (i.e NewEndpoint can be called without a port and in this case it will be automatically filled with the listen port)

This was removed in PR #23: https://github.com/WhoSoup/factom-p2p/pull/23/files#diff-f109c77a04da64350f07a2bce8f8e69cR259. Endpoint should now always have a host and port
