### ISSUE TITLE
feedback on runCatRound function

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#17]
Commenting on https://github.com/WhoSoup/factom-p2p/blob/master/controller_cat.go#L10

1.
```golang
	if time.Since(c.lastRound) < c.net.conf.RoundTime {
		return
	}
	c.lastRound = time.Now()
```
I think we can improve that pattern: why not have runCatRound in its own gorountine with an infinite loop that is blocked by a Ticker set to RoundTime? That would be cleaner (avoid unecessary evaluations) and more idiomatic I think and avoid doing this manual handling of event loop. 

2. `c.net.conf.Drop` took me too long to understand it was the target to drop to and not the number of connections to drop (yeah I saw there is a comment on that line but brain was hard wired to not believe it because of the name :D). Then I looked at https://github.com/WhoSoup/factom-p2p/blob/master/configuration.go#L53 and realized I cannot make sense of most of the CAT parameters without digging the code. e.g `Max` what? I'd appreciate to see a short comment next to each of those CAT parameters explaining them.

**Comment by WhoSoup** [comment]
1. Doing it this way gives the "run" loops a deterministic order. First it drops peers, then it does metrics and pings, rather than doing pinging/metrics for peers that are going to be dropped. I'm not sure if the cost of doing a time-check once a second is more expensive than keeping the cat loop in the scheduler, though I assume both are negligible

2. Yeah, that confuses even me sometimes. I'll change it to DropTo

**Comment by PaulBernier** [comment]
I think that issue can be closed
