### ISSUE TITLE
Usage of gob

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#20]
from https://golang.org/src/encoding/gob/decoder.go

```golang
// The Decoder does only basic sanity checking on decoded input sizes,
// and its limits are not configurable. Take caution when decoding gob data
// from untrusted sources.
```
It seems that the decoder will read up to 8Gb of data before considering it too big. Is there any safe guard against an attack that would submit huge messages? Does the current p2p protect itself from that? What do they mean by `Take caution when decoding gob data` exactly if limits are not configurable? :thinking:

**Comment by PaulBernier** [comment]
Gob has also the problem that it's Golang specific which is not great for interoperability. I think we should aim to move away from gob (geth doesn't use gob, its reads from tcp connections using short byte buffers, which is safer and more efficient). Maybe it's too much to ask for this iteration, but I think that should be the number 1 item on the todo list for a v11 of the protocol.

**Comment by WhoSoup** [comment]
> Is there any safe guard against an attack that would submit huge messages? Does the current p2p protect itself from that?

Yes, via deadlines which are set in the config with a default of 5 minutes. This number comes from testing last year: https://github.com/FactomProject/factomd/pull/666. I'd love to have a shorter timeout but there are instances where nodes take between 1 and 5 minutes to send a message, unfortunately. 

8 GiB / 5 Minutes is ~1.1 Gbps, so nodes would need more than a gigabit connection in order to theoretically reach the golang limit in this time.

> What do they mean by `Take caution when decoding gob data` exactly if limits are not configurable? 🤔

Probably not infinitely reading from a source. To do that, we'd have to send two messages, one with the size of the next message, then the Gob message itself. However, gob is self-delimiting already so the p2p1 code doesn't have a size message. Changing that unfortunately requires altering the protocol, and for that see below.  

> Gob has also the problem that it's Golang specific which is not great for interoperability. I think we should aim to move away from gob (geth doesn't use gob, its reads from tcp connections using short byte buffers, which is safer and more efficient). Maybe it's too much to ask for this iteration, but I think that should be the number 1 item on the todo list for a v11 of the protocol.

That's the plan. The problem with changing the protocol like this is that it's a really nasty hard fork where the entire network has to migrate and form a new network. At the moment, the only way to talk to p2p1 nodes is by sending a Gob message to determine which protocol they're running. After that, it's possible to upgrade the protocol to something else but it's somewhat complicated because you have to extract gob's internal buffer to begin with, since it may have already buffered part of the next message.

My original idea was for V10 to be Protobuf, but that has its own issues since it's not a streaming format and they [advise against using protobuf for messages larger than 1MB](https://developers.google.com/protocol-buffers/docs/techniques#large-data). 

The current migration plan is:
1. Produce code that is capable of handling multiple protocols (done)
2. Roll out new code to nodes running V11 (capable of detecting an incoming protocol that isn't gob)
3. Deprecate nodes before version 6.5 (or whatever it ends up being)
4. Wait a very long time
5. Enable Vxx, which will kick out all outdated nodes

Now, step 5 is something that might never end up happening but I'd estimate that it's going to be timed with some other hard fork in the distant future. 

Between 2. and 5. we can also introduce a number of other protocols that still rely on the V9 handshake mechanism, so Gob -> upgrade to something else. That's the plan for V11.

**Comment by PaulBernier** [comment]
I wasn't aware of the read deadline, great.
Migration plan makes perfect sense. Thanks.
