### ISSUE TITLE
holdall issue

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#33]
I think I have reviewed at least once every file... I will still take a deep breadth and a step back to see the big picture again, but I think I am basically done with the review. 

Here are just a few leftover comments that I batched together:

1. It doesn't sound right that the Controller does the `parseSpecial` logic from a separation of concerns point of view, it looks like this is the job of a configuration parser that should happen ahead. The `bootstrap` endpoints don't come as raw strings, they are provided already parsed, so why not the same for special endpoints?

2. I was thinking that `ToNetwork` and `FromNetwork` may need separate capacity configuration because the rate of inbound vs outbound messages can be very different. I was also thinking it would be nice at add the FillRatio of both ToNetwork/FromNetwork to Prometheus metrics. (bonus)

3. I am not sure you need that configuration copy here: https://github.com/WhoSoup/factom-p2p/blob/master/network.go#L41 because the function argument is already a fresh copy you can work on. Also on line 67/68 you work on the old `conf` variable instead of your copy `myconf` which is odd. So I'd suggest sticking to the `conf` argument all the way?

**Comment by WhoSoup** [comment]
1. Factomd has the ability to change the "special" peers at runtime when the config is reloaded (see `Network.SetSpecial`) Hence the parsing of special peers is done in the controller.

2. The current number is a legacy value used by p2p1 that's just "big enough to not have to worry about it." Theoretically, all the channels could be fairly small in size and it would only be a problem if we're trying to send data faster than the peer can handle (which we can't do anything about). Properly investigating it is going to take a lot of time, since there are some quirks of golang associated with it.  
Basically goroutines are scheduled cooperatively, so what usually ends up happening if there are multiple queues that all need to be emptied, it will work off all the items of a single queue before moving on to the next one, rather than interleaving them. A short example of this behavior: https://play.golang.org/p/UR64lMdSCb6  
This makes it very hard to gauge the size channels need, since there are natural occurrences where golang is just busy working off a single queue and lets the others "pile up". For that reason, I've just left them at 5000 for now.  
One solution might be to rely more on blocking channels internally so that peers will just stop reading from the tcp connection until the queues are being emptied, which would let us work with very small channels. I haven't had time to investigate how well that would work yet.

3. looks like you're right. I was worried that since Sanitize() operates on a pointer, it might overwrite the function caller, but the parameter is already a copy: https://play.golang.org/p/B4ydkCOBJ4t

**Comment by PaulBernier** [comment]
Oh very interesting comment about goroutine scheduler, I am going to go read more on the topic, thanks!

Another idea, what do you think about Network not directly exposing publicly `ToNetwork` and `FromNetwork` but instead exposing a `Send` and `Reader` methods of Network to be used by the client of the p2p package. In the spirit of hiding internal implementation and forcibly preventing the client of misusing the ParcelChannel instances.

**Comment by WhoSoup** [comment]
> Another idea, what do you think about Network not directly exposing publicly `ToNetwork` and `FromNetwork` but instead exposing a `Send` and `Reader` methods of Network to be used by the client of the p2p package. In the spirit of hiding internal implementation and forcibly preventing the client of misusing the ParcelChannel instances.

The only misuse I can think of is sending to FromNetwork and reading from ToNetwork, so I'm not sure how much more advantageous it would be to hide that. The advantage of ParcelChannel is that you can still use it as a regular, blocking channel and use the Send() method for non-blocking by dropping older messages rather than new ones.

To mask that, it would be something like:
```
func (Network) Send(Parcel)
func (Network) BlockingSend(Parcel)
func (Network) Reader() <-chan *Parcel
```

Was that what you had in mind or something different?

**Comment by PaulBernier** [comment]
That's exactly what I had in mind. Actually I didn't really realize that ParcelChannel was directly extending a regular channel and that blocking send was an option. With those 3 interfaces you mention that would be clean and clear.

**Comment by WhoSoup** [comment]
More on the current channel structure:

I think there are four ways to go about bringing the data from peers to the applications.

1. (The current way) After receiving data, it's stuffed into a non-blocking channel. The controller passes application parcels into a non-blocking channel to the app.\
\
The downside in this instance is the scheduler, so the non-blocking channels need to be large enough to accommodate the buildup or there will be data loss.
2. (Avoid the scheduler problem) Each peer has its own channel for data. The controller has one (or more) goroutine that polls the peers and reads their data. Since the poll is timer based, the scheduler is "forced" to prioritize it and there is no buildup.\
\
The downside is that this is increased CPU usage (minimal) and the channel to the application would still need to be large, since we don't know if the app will also poll or not.
\
The upside is we can get away with tiny channels internally, saving memory.
3. (Block it all) Similar to the current way, but use blocking channels internally. This means that a peer reading data will only be able to deliver the parcel if the controller takes it off their hands. 
\
The downside is that it might turn the controller's data-reading-loop into a bottleneck, depending how fast the switching works. I'd have to benchmark it. The upside is the channels could be kept very small without data loss.
4. (Callbacks) Get rid of delivery channels for data and just use callbacks to react based on parcel type. The application would be able to register a `func(*Parcel)` callback for application parcels and if the app wants to use channels, they can create one of their own and feed it from the callbacks.\
\
The downside is that it's not "clean" and the p2p package has no control over how long the callback function takes. If the callback is turned into a goroutine, the scheduler can potentially call parcels out of order, which is not optimal for apps.

I'm gonna have to play around with a couple of these and see how well they work

**Comment by WhoSoup** [comment]
Came another variant, which is manually messing with golang's scheduler via using `runtime.Gosched()`. If you compare the previous example with one using Gosched: https://play.golang.org/p/Ok8t8BFRDVv The output becomes more like something you'd expect. This is usually done for tight forever loops that have a chance of locking up a thread but it could help alleviate the data-hogging of parcel channels.

**Comment by PaulBernier** [comment]
I am not pushing to analyse in details the best channel strategy for `From/ToNetwork` for now, but I think we should really publish Prometheus metrics about it at least so we get some visibility. As you said it's very hard to get an idea of how those would fill *in real condition*, or even just now what kind of throughput we are going to get/need. Those metrics could be invaluable for future improvements.

Metrics would be the fill ratio and a counter of the nb of parcels.
