### ISSUE TITLE
select with single blocking case

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#4]
I noticed you have a select with a single case and no default: https://github.com/WhoSoup/factom-p2p/blob/master/controller_routing.go#L31

I think the select is unecessary in this case while adding a layer of indentation.

**Comment by WhoSoup** [comment]
That used to be where the check for shutting down the network goes, which will be implemented again at some point (I removed it because it was an unnecessary complexity during debugging and it's easier to add toward the end).

I'm going to fix this at a later point when shutdown functionality is implemented

**Comment by PaulBernier** [comment]
Got it, I guess there is no need to keep that issue open then.
