### ISSUE TITLE
How does p2p behave behind a reverse proxy?

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#7]
I haven't read all the parts of the code yet, but I was wondering if you took into account the case factomd is sitting behind a reverse proxy, for instance a simple nginx? In this case `RemoteAddr` will be the same for all peers (different ports of course though), could that be a problem anywhere in your code? It may be a problem with the "ban" feature as it becomes impossible to ban a specific remote IP? Probably the existing code has the same "problems", just wondering if you thought about that case.

**Comment by WhoSoup** [comment]
Peers are identified by their Hash, which is `ip:port 4-byte-nodeid`, where the nodeid is self-reported. Assuming that ip:port are always the same, a peer connecting with the same nodeid as another peer will cause the first peer's connection to be dropped and replaced by the new peer. That's intended functionality to allow peers to quickly reconnect and "take over" their old connection, but still allow for several nodes to sit behind a NAT.

The nodeid is set in the config but factomd will assign it a randomly generated number on startup, meaning the collision likelihood is about 1 in 4294967296. For the most part, this means p2p should work fine.

The problems that come in:
* The node will only share the reverse proxy ip with others, which is undesirable but not harmful
* Should the node ever try to connect to itself, it will ban the endpoint for 50 years. If the reverse-proxy allows this, the node would essentially disable itself

I'm not too familiar with TCP reverse proxies, but if they support features to pass through the original IP to the node, everything will work fine. Otherwise, a solution could be to have a "NoSelfBan" configuration option that would prevent loopback connections but not ban itself.

**Comment by PaulBernier** [comment]
Ok cool, good to know, thanks.

I had my personal experience with Orax in mind when asking that question. But actually it uses WebSockets, which starts with an HTTP handshake which gives an opportunity for the reverse proxy to forward the real IP of the user in a HTTP header. But I don't think a bare TCP proxy can do such things :thinking:
