### ISSUE TITLE
Shoudn't Peer#Send return boolean of success?

### ISSUE THREAD

**Issue by PaulBernier** [WhoSoup/factom-p2p#9]
https://github.com/WhoSoup/factom-p2p/blob/master/peer.go#L240
Why not propagate the boolean about success? I can see at least 1 place where it could be used: https://github.com/WhoSoup/factom-p2p/blob/master/controller_cat.go#L142 in case the message doesn't go through you could skip the 5s timeout

**Comment by WhoSoup** [comment]
I decided to not return a boolean for Send because it's not indicative of a successful send. It only indicates that the message has been successfully added to the end of the send-queue. Sending itself happens asynchronously.

The queue only returns false if the queue is getting so hammered that it can't drop packets fast enough to add one, which could be an indicator of misconfiguration. It's mostly useful outside of the p2p package, since the Network's ToNetwork.Send() is the same type.
